name: Docker SBOM Scan and Insights

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      packages: read
      id-token: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true 
          tags: python-app:${{ github.sha }}

      # - name: Generate and Submit SBOM
      #   uses: anchore/sbom-action@v0
      #   with:
      #     image: python-app:${{ github.sha }}
      #     format: spdx-json
      #     output-file: sbom.spdx.json
      #     # This specific flag sends the data to GitHub Insights -> Dependency Graph
      #     dependency-snapshot: false
      - name: Generate and Submit SBOM to Dependency Graph
        uses: aquasecurity/trivy-action@0
        with:
          scan-type: 'image'
          image-ref: 'python-app:${{ github.sha }}'
          # 'github' format formats the output specifically for the Dependency API
          format: 'github'
          output: 'dependency-results.sbom.json'
          # Passing the token triggers the automatic upload to the Dependency tree
          github-pat: ${{ secrets.GITHUB_TOKEN }}
